"""Initial migration

Revision ID: 8d6a44798fa0
Revises: 
Create Date: 2025-04-01 03:19:19.991029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d6a44798fa0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('firstName', sa.String(length=50), nullable=False),
    sa.Column('lastName', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('patients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('firstName', sa.String(length=50), nullable=False),
    sa.Column('lastName', sa.String(length=50), nullable=False),
    sa.Column('dateOfBirth', sa.String(length=10), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('insuranceId', sa.String(length=50), nullable=False),
    sa.Column('medicalConditions', app.MedicalConditionList(), nullable=True),
    sa.Column('allergies', app.AllergiesList(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('profileImageUrl', sa.String(length=500), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.Column('createdBy', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['createdBy'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('medical_images',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patientId', sa.String(length=36), nullable=False),
    sa.Column('imageUrl', sa.String(length=500), nullable=False),
    sa.Column('imageType', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uploadedAt', sa.DateTime(), nullable=True),
    sa.Column('uploadedBy', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['patientId'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['uploadedBy'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medical_images')
    op.drop_table('patients')
    op.drop_table('users')
    # ### end Alembic commands ###
