"""Initial migration

Revision ID: 93a6093d64af
Revises: 
Create Date: 2025-04-21 22:40:21.634061

"""
from alembic import op
import sqlalchemy as sa
from app import MedicalConditionList, AllergiesList


# revision identifiers, used by Alembic.
revision = '93a6093d64af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('firstName', sa.String(length=50), nullable=False),
    sa.Column('lastName', sa.String(length=50), nullable=False),
    sa.Column('dateOfBirth', sa.String(length=10), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('insuranceId', sa.String(length=50), nullable=True),
    sa.Column('medicalConditions', MedicalConditionList(), nullable=True),
    sa.Column('allergies', AllergiesList(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('profileImageUrl', sa.String(length=500), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.Column('createdBy', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['createdBy'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('appointments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patientId', sa.String(length=36), nullable=False),
    sa.Column('doctorId', sa.String(length=36), nullable=False),
    sa.Column('appointmentDate', sa.String(length=10), nullable=False),
    sa.Column('startTime', sa.String(length=8), nullable=False),
    sa.Column('endTime', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctorId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patientId'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medical_images',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patientId', sa.String(length=36), nullable=False),
    sa.Column('imageUrl', sa.String(length=500), nullable=False),
    sa.Column('imageType', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uploadedAt', sa.DateTime(), nullable=True),
    sa.Column('uploadedBy', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['patientId'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['uploadedBy'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medical_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patientId', sa.String(length=36), nullable=False),
    sa.Column('doctorId', sa.String(length=36), nullable=False),
    sa.Column('visitDate', sa.String(length=10), nullable=False),
    sa.Column('chiefComplaint', sa.String(length=200), nullable=False),
    sa.Column('diagnosis', sa.Text(), nullable=False),
    sa.Column('treatmentPlan', sa.Text(), nullable=False),
    sa.Column('followUpNeeded', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctorId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patientId'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patientId', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('dosage', sa.String(length=50), nullable=False),
    sa.Column('frequency', sa.String(length=100), nullable=False),
    sa.Column('startDate', sa.String(length=10), nullable=False),
    sa.Column('endDate', sa.String(length=10), nullable=True),
    sa.Column('prescribedBy', sa.String(length=36), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patientId'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['prescribedBy'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medications')
    op.drop_table('medical_records')
    op.drop_table('medical_images')
    op.drop_table('appointments')
    op.drop_table('patients')
    # ### end Alembic commands ###
